name: SpringBoot CI

#When to run the workflow
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
#What jobs to run
jobs:
  #job name
  build-and-test:
    #Runner environment machine 
    runs-on: ubuntu-latest
    #Job steps
    steps:
      #Step 1: Checkout code so runner can access it
      - name: Checking out code
        #consumes action from Github actions marketplace
        uses: actions/checkout@v4

      #Step 2: Set up JDK 21
      - name: Set up JDK 21 (Setting java)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      #Step 3: Build and test with Maven
      - name: Build and Test with Maven
        run: ./mvnw clean package
    